import { type MuscleDefinition } from "../types/types";


export const MUSCLES: MuscleDefinition[] = [
    {
        _id: 'sys-chest',
        name: 'Chest',
        region: 'Upper Body',
        group: 'Chest',
        isAnterior: true,
        isCustom: false,
    },

    {
        _id: 'sys-lats',
        name: 'Lats',
        region: 'Upper Body',
        group: 'Back',
        isAnterior: false,
        isCustom: false,
    },
    {
        _id: 'sys-traps',
        name: 'Traps',
        region: 'Upper Body',
        group: 'Back',
        isAnterior: false,
        isCustom: false,
    },
    {
        _id: 'sys-lower-back',
        name: 'Lower Back',
        region: 'Upper Body',
        group: 'Back',
        isAnterior: false,
        isCustom: false,
    },
    {
        _id: 'sys-rhomboids',
        name: 'Rhomboids',
        region: 'Upper Body',
        group: 'Back',
        isAnterior: false,
        isCustom: false,
    },
    {
    _id: 'sys-front-delts',
    name: 'Front Delts',
    region: 'Upper Body',
    group: 'Shoulders',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-side-delts',
    name: 'Side Delts',
    region: 'Upper Body',
    group: 'Shoulders',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-rear-delts',
    name: 'Rear Delts',
    region: 'Upper Body',
    group: 'Shoulders',
    isAnterior: false,
    isCustom: false,
  },
  {
    _id: 'sys-biceps',
    name: 'Biceps',
    region: 'Upper Body',
    group: 'Arms',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-triceps',
    name: 'Triceps',
    region: 'Upper Body',
    group: 'Arms',
    isAnterior: false,
    isCustom: false,
  },
  {
    _id: 'sys-forearms',
    name: 'Forearms',
    region: 'Upper Body',
    group: 'Arms',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-abs',
    name: 'Abs',
    region: 'Core',
    group: 'Torso',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-obliques',
    name: 'Obliques',
    region: 'Core',
    group: 'Torso',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-quads',
    name: 'Quads',
    region: 'Lower Body',
    group: 'Legs',
    isAnterior: true,
    isCustom: false,
  },
  {
    _id: 'sys-hamstrings',
    name: 'Hamstrings',
    region: 'Lower Body',
    group: 'Legs',
    isAnterior: false,
    isCustom: false,
  },
  {
    _id: 'sys-glutes',
    name: 'Glutes',
    region: 'Lower Body',
    group: 'Legs',
    isAnterior: false,
    isCustom: false,
  },
  {
    _id: 'sys-calves',
    name: 'Calves',
    region: 'Lower Body',
    group: 'Legs',
    isAnterior: false,
    isCustom: false,
  }
]

