import type { Exercise } from "../types/types";

export const MOCK_EXERCISES: Exercise[] = [
    {
  _id: 'ex-lat-pulldown',
  name: 'Lat Pulldown',
  description: 'A compound upper-body pulling exercise performed on a cable machine that targets the latissimus dorsi, rhomboids, and biceps.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-lats',
      name: 'Lats',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-rhomboids',
      name: 'Rhomboids',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-biceps',
      name: 'Biceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-rear-delts',
      name: 'Rear Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['back', 'pull', 'cable', 'vertical pull', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-lat-pulldown-machine',
      name: 'Lat Pulldown Machine',
      description: 'Cable station equipped with an overhead pulley, adjustable thigh pads, and wide attachment bar.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-lat-pulldown-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-lat-pulldown-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 45,
  instructions: [
    'Adjust the thigh pads so your knees are secured firmly with feet flat on the floor.',
    'Grip the bar slightly wider than shoulder-width with an overhand grip.',
    'Depress your scapulae and pull the bar smoothly toward your upper chest, leading with your elbows.',
    'Squeeze your lats at the bottom without excessively leaning back.',
    'Control the eccentric phase until your arms are fully extended overhead.',
  ],
  notes: [
    'Avoid using excessive backward momentum or swinging to move the weight.',
    'Keep your chest proud throughout the range of motion.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-incline-dumbbell-chest-supported-row',
  name: 'Incline Dumbbell Chest-Supported Row',
  description: 'An upper-back row performed prone on an incline bench using heavy dumbbells, eliminating lower back strain and stabilizing the torso.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-rhomboids',
      name: 'Rhomboids',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-traps',
      name: 'Traps',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-rear-delts',
      name: 'Rear Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-lats',
      name: 'Lats',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-biceps',
      name: 'Biceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['back', 'row', 'dumbbell', 'chest supported', 'horizontal pull', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-adjustable-bench',
      name: 'Incline Bench',
      description: 'Standard adjustable weight bench set to a 30 to 45-degree angle.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      _id: 'eq-dumbbells',
      name: 'Dumbbells',
      description: 'Pairs of free-weight dumbbells.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-csr-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-csr-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 45,
  instructions: [
    'Set an adjustable bench to an incline angle between 30 and 45 degrees.',
    'Lie chest-down against the pad with your feet planted securely behind you for support.',
    'Grip a dumbbell in each hand with arms hanging straight down in a neutral or slightly semi-pronated grip.',
    'Retract your shoulder blades and pull your elbows back and up toward your hips.',
    'Squeeze your upper back and rear delts at peak contraction, then slowly lower the dumbbells under control to full hang.',
  ],
  notes: [
    'Keep your sternum pressed into the bench pad to avoid hyperextending your lumbar spine.',
    'Allow your shoulder blades to protract slightly at the bottom for a full stretch.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-reverse-pec-deck-fly',
  name: 'Reverse Pec Deck Fly',
  description: 'An isolation machine movement targeting the posterior deltoids and upper back muscles through horizontal shoulder abduction.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-rear-delts',
      name: 'Rear Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-rhomboids',
      name: 'Rhomboids',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-traps',
      name: 'Traps',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['shoulders', 'rear delts', 'machine', 'isolation', 'upper back'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-pec-deck-machine',
      name: 'Reverse Pec Deck / Fly Machine',
      description: 'Pin-loaded machine with adjustable arms and chest support pad.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-rev-fly-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-rev-fly-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Adjust the seat height so the handles are roughly at shoulder height when seated.',
    'Sit facing the pad with your chest firmly supported and feet flat on the floor.',
    'Grip the handles with a neutral or pronated grip and maintain a slight bend in your elbows.',
    'Drive the handles out and back in a wide arc using your rear deltoids until your arms are aligned with your torso.',
    'Control the weight slowly back to the starting position without letting the stack slam.',
  ],
  notes: [
    'Keep your shoulders depressed down away from your ears to prevent upper trap dominance.',
    'Avoid excessively shrugging or throwing your torso back off the pad.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-standing-cable-bicep-curl',
  name: 'Standing Cable Bicep Curl',
  description: 'An isolation exercise that utilizes constant cable tension to load elbow flexion across the entire range of motion.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-biceps',
      name: 'Biceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-forearms',
      name: 'Forearms',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['arms', 'biceps', 'cable', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-cable-pulley-station',
      name: 'Cable Pulley Station',
      description: 'Adjustable low cable pulley equipped with a straight or EZ-curl bar attachment.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-cable-curl-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-cable-curl-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Set the cable pulley to the lowest notch and attach a straight or EZ-curl bar.',
    'Stand facing the pulley, grip the bar shoulder-width underhand (supinated), and step back slightly for initial tension.',
    'Pin your elbows by your ribs, brace your core, and curl the bar upward toward your shoulders.',
    'Contract your biceps firmly at the top without swinging your hips or shoulders.',
    'Slowly lower the bar back down under control until your arms reach full extension.',
  ],
  notes: [
    'Keep your elbows stationary at your sides rather than drifting forward to recruit the anterior deltoids.',
    'Maintain a neutral wrist position throughout the curl to protect the joints.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-dumbbell-hammer-curl',
  name: 'Dumbbell Hammer Curl',
  description: 'An elbow flexion variation performed with a neutral grip to target the brachialis, brachioradialis, and biceps brachii.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-biceps',
      name: 'Biceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-forearms',
      name: 'Forearms',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['arms', 'biceps', 'forearms', 'dumbbell', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-dumbbells',
      name: 'Dumbbells',
      description: 'Pairs of free-weight dumbbells.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-hammer-curl-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-hammer-curl-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Stand tall or sit upright with a dumbbell in each hand, arms hanging at your sides with palms facing inward (neutral grip).',
    'Keep your elbows pinned close to your torso and shoulders relaxed.',
    'Curl the weights upward while maintaining the neutral wrist position until your forearms are nearly vertical.',
    'Squeeze the brachialis and forearms at the peak contraction.',
    'Lower the dumbbells slowly under control to full elbow extension.',
  ],
  notes: [
    'Do not swing your torso or use momentum from your hips to start the lift.',
    'Keep your wrists rigid and neutral; avoid flexing or extending the wrist joint.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-machine-chest-press',
  name: 'Machine Chest Press',
  description: 'A seated horizontal pressing machine exercise that provides guided stabilization to target the pectoralis major, front delts, and triceps.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-chest',
      name: 'Chest',
      region: 'Upper Body',
      group: 'Chest',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-front-delts',
      name: 'Front Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-triceps',
      name: 'Triceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['chest', 'push', 'machine', 'compound', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-seated-chest-press-machine',
      name: 'Seated Chest Press Machine',
      description: 'Pin-loaded or plate-loaded seated chest press station with adjustable seat and handles.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-chest-press-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-chest-press-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 45,
  instructions: [
    'Adjust the seat height so the handles align roughly with mid-to-lower chest level.',
    'Sit back with head, upper back, and glutes firmly against the backrest, feet planted flat on the floor.',
    'Grip the handles, retract and depress your scapulae, and brace your core.',
    'Press the handles forward smoothly by contracting your chest until your arms are extended without locking the elbows.',
    'Slowly reverse the movement, controlling the descent until you feel a deep, comfortable stretch in your chest.',
  ],
  notes: [
    'Avoid letting your shoulders roll forward at the end of the press; keep scapulae retracted.',
    'Control the eccentric tempo so the weight stack does not slam between repetitions.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-dumbbell-chest-fly',
  name: 'Dumbbell Chest Fly',
  description: 'An isolation exercise performed lying on a flat bench that stretches and contracts the pectoralis major through horizontal adduction.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-chest',
      name: 'Chest',
      region: 'Upper Body',
      group: 'Chest',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-front-delts',
      name: 'Front Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['chest', 'isolation', 'dumbbell', 'hypertrophy', 'fly'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-flat-bench',
      name: 'Flat Bench',
      description: 'Standard horizontal weight bench.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      _id: 'eq-dumbbells',
      name: 'Dumbbells',
      description: 'Pairs of free-weight dumbbells.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-chest-fly-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-chest-fly-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 45,
  instructions: [
    'Lie flat on a bench holding a dumbbell in each hand directly above your chest with palms facing each other.',
    'Maintain a slight, fixed bend at your elbows throughout the movement.',
    'Lower the dumbbells out to the sides in a wide arc until you feel a comfortable stretch across your pectorals.',
    'Engage your chest to bring the dumbbells back together in the same wide arc over the center of your chest.',
    'Squeeze the pectorals at the top before beginning the next repetition.',
  ],
  notes: [
    'Do not allow your elbows to drop excessively below the bench level to protect your shoulder joints.',
    'Keep your elbow bend angle rigid; turning the movement into a press removes tension from the chest.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-tricep-cable-pushdown',
  name: 'Triceps Cable Pushdown',
  description: 'An elbow extension exercise using a high cable pulley to isolate all three heads of the triceps brachii with continuous tension.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-triceps',
      name: 'Triceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-forearms',
      name: 'Forearms',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['arms', 'triceps', 'cable', 'isolation', 'hypertrophy', 'pushdown'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-cable-pulley-station',
      name: 'Cable Pulley Station',
      description: 'High cable pulley equipped with a rope or straight bar attachment.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-tricep-pushdown-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-tricep-pushdown-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Set the cable pulley to the highest position and attach a straight bar or rope.',
    'Grip the attachment firmly, stand upright with a slight forward torso lean, and pin your elbows to your sides.',
    'Extend your arms downward by contracting your triceps until your elbows are fully locked out.',
    'Hold the peak contraction for a brief pause at the bottom.',
    'Slowly allow the attachment to rise under control until your forearms pass parallel to the floor.',
  ],
  notes: [
    'Keep your elbows tucked into your ribs and stationary throughout the movement; do not let them flare or drift forward.',
    'Avoid hunching over the attachment to use body weight to push the load down.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-dumbbell-lateral-raise',
  name: 'Dumbbell Lateral Raise',
  description: 'An isolation exercise performed by abducting the arms laterally to isolate the lateral (side) deltoids for shoulder width.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-side-delts',
      name: 'Side Delts',
      region: 'Upper Body',
      group: 'Shoulders',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-traps',
      name: 'Traps',
      region: 'Upper Body',
      group: 'Back',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['shoulders', 'lateral delts', 'dumbbell', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-dumbbells',
      name: 'Dumbbells',
      description: 'Pairs of free-weight dumbbells.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-lat-raise-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-lat-raise-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Stand upright with dumbbells held at your sides or slightly in front of your thighs, palms facing inwards.',
    'Maintain a slight bend at the elbows and a subtle forward torso lean.',
    'Raise your arms out to the sides in the scapular plane (roughly 15 to 30 degrees forward from purely lateral) until parallel to the floor.',
    'Pause briefly at the top without letting your upper traps shrug up toward your ears.',
    'Lower the dumbbells slowly under control to return to the starting position.',
  ],
  notes: [
    'Avoid swinging the hips or using leg drive to propel the dumbbells up.',
    'Lead the movement with your elbows and side deltoids rather than your wrists.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-overhead-cable-triceps-extension',
  name: 'Overhead Cable Triceps Extension',
  description: 'An overhead extension using a rope attachment on a cable pulley to place the long head of the triceps under a deep loaded stretch.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-triceps',
      name: 'Triceps',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-forearms',
      name: 'Forearms',
      region: 'Upper Body',
      group: 'Arms',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['arms', 'triceps', 'cable', 'overhead', 'isolation', 'long head'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-cable-pulley-station',
      name: 'Cable Pulley Station',
      description: 'Adjustable cable tower equipped with a triceps rope attachment.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-overhead-ext-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-overhead-ext-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Set the cable pulley around chest or shoulder height and attach a double-rope.',
    'Grip the ropes, turn away from the cable stack, and step forward into a staggered stance with a forward torso lean.',
    'Position your elbows forward overhead and bend your arms so your hands are behind your head.',
    'Extend your forearms forward and overhead by contracting your triceps until your arms are fully straight.',
    'Spread the rope ends apart at full lockout, then return slowly to allow a deep stretch in the long head of the triceps.',
  ],
  notes: [
    'Keep your upper arms and elbows fixed in place; do not let your elbows flare excessively outward or drop.',
    'Brace your core to keep your lower back from arching under the backward pull of the cable.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-leg-extension',
  name: 'Leg Extension',
  description: 'An open-kinetic-chain isolation movement performed on a machine to isolate all four heads of the quadriceps femoris.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-quads',
      name: 'Quads',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['legs', 'quads', 'machine', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-leg-extension-machine',
      name: 'Leg Extension Machine',
      description: 'Pin-loaded seated leg extension station with adjustable backrest and lower shin pad.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-leg-ext-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-leg-ext-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Adjust the backrest so your knees align directly with the machine pivot axis.',
    'Position the padded lever so it rests comfortably against your lower shins just above the ankles.',
    'Grip the side handles firmly and pull yourself down into the seat to keep your hips locked in place.',
    'Extend your legs upward by contracting your quadriceps until your knees are fully extended.',
    'Pause briefly at the peak contraction, then lower the weight under control back to the starting point.',
  ],
  notes: [
    'Avoid letting your glutes lift off the seat pad during the extension.',
    'Do not kick or use ballistic momentum to drive the weight up.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-lying-leg-curl',
  name: 'Lying Leg Curl',
  description: 'An isolation machine exercise performed prone that targets knee flexion to develop the hamstring muscle group.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-hamstrings',
      name: 'Hamstrings',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-calves',
      name: 'Calves',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['legs', 'hamstrings', 'machine', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-lying-leg-curl-machine',
      name: 'Lying Leg Curl Machine',
      description: 'Prone leg curl bench with angled torso pad, side handles, and adjustable roller pad.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-leg-curl-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-leg-curl-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Lie face down on the bench with the machine pivot aligned with your knee joints.',
    'Adjust the roller pad to sit just below your calves on the Achilles tendon area.',
    'Grip the handles at the front and press your hips down firmly into the bench.',
    'Curl your heels toward your glutes in a smooth arc by contracting your hamstrings.',
    'Squeeze your hamstrings at the top, then slowly lower the roller pad back to the starting position under control.',
  ],
  notes: [
    'Keep your pelvis pinned to the bench to avoid overarching the lower back.',
    'Maintain dorsiflexion or neutral ankle position to keep the tension centered on the hamstrings.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-glute-kickback-machine',
  name: 'Machine Glute Kickback',
  description: 'A unilateral lower-body machine exercise isolating hip extension to target the gluteus maximus without spinal loading.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-glutes',
      name: 'Glutes',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-hamstrings',
      name: 'Hamstrings',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['legs', 'glutes', 'machine', 'unilateral', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-glute-kickback-machine',
      name: 'Standing Glute Kickback Machine',
      description: 'Pin-loaded or plate-loaded standing machine featuring a chest/forearm support and a rear kick pad.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-kickback-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-kickback-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: true,
  estimatedDuration: 45,
  instructions: [
    'Position your chest and forearms against the front support pads, gripping the handles firmly.',
    'Place the sole of your working foot or the back of your knee against the movement lever pad.',
    'Keep your supporting leg slightly bent and brace your core.',
    'Drive the lever pad back and slightly up by contracting your glute until your hip is fully extended.',
    'Pause for a second at peak glute contraction, then slowly return to the starting position under control.',
  ],
  notes: [
    'Avoid hyperextending your lower back to get extra range of motion; movement should come strictly from the hip.',
    'Keep your hips square to the machine rather than rotating outward.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-seated-hip-abduction-machine',
  name: 'Seated Hip Abduction Machine',
  description: 'A seated machine isolation movement that works hip abduction against resistance to target the gluteus medius and minimus.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-glutes',
      name: 'Glutes',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['legs', 'glutes', 'machine', 'abductors', 'isolation', 'hip health'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-hip-abductor-machine',
      name: 'Seated Hip Abduction Machine',
      description: 'Pin-loaded seated machine equipped with outer thigh pads and adjustable starting angle.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-abductor-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-abductor-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Sit down on the machine with your back flat against the pad and place your feet on the footrests.',
    'Position the leg pads so they rest against the outside of your knees/thighs.',
    'Select a starting width that allows a deep, comfortable stretch without straining your hips.',
    'Push the pads outward smoothly using your outer hips and glutes until your legs are fully spread.',
    'Hold the contraction briefly, then slowly control the pads back inward without allowing the weight stack to touch down.',
  ],
  notes: [
    'Keep your pelvis pushed firmly back into the seat throughout the set.',
    'Do not use jerky momentum or bounce at the innermost point of the movement.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-leg-press-45',
  name: '45-Degree Leg Press',
  description: 'A closed-kinetic-chain multi-joint lower body movement performed on an angled sled, heavily recruiting the quadriceps, glutes, and hamstrings.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-quads',
      name: 'Quads',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: true,
      isCustom: false,
    },
    {
      _id: 'sys-glutes',
      name: 'Glutes',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-hamstrings',
      name: 'Hamstrings',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-calves',
      name: 'Calves',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['legs', 'quads', 'glutes', 'machine', 'compound', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-45-leg-press-machine',
      name: '45-Degree Leg Press Machine',
      description: 'Plate-loaded or pin-loaded angled sled equipped with an adjustable backrest and wide footplate.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-leg-press-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-leg-press-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 50,
  instructions: [
    'Sit on the machine with your back and head firmly against the padded backrest.',
    'Place your feet shoulder-width apart in the center of the platform with toes angled slightly outward.',
    'Release the safety catches and lower the sled under control until your knees are bent at roughly 90 degrees.',
    'Drive through your whole foot to push the platform back up to the starting position.',
    'Extend your legs fully without snapping or violently locking out your knees.',
  ],
  notes: [
    'Keep your lower back and glutes pressed flat against the seat; do not allow your pelvis to tuck or round (butt wink).',
    'Ensure your knees track in line with your toes throughout the entire movement.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-standing-calf-raise-machine',
  name: 'Standing Calf Raise Machine',
  description: 'An ankle plantarflexion isolation exercise performed on a dedicated machine with straight knees to heavily target the gastrocnemius.',
  category: 'strength',
  muscles: [
    {
      _id: 'sys-calves',
      name: 'Calves',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
  ],
  tags: ['legs', 'calves', 'machine', 'isolation', 'hypertrophy'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-standing-calf-raise-machine',
      name: 'Standing Calf Raise Machine',
      description: 'Pin-loaded or plate-loaded standing station with shoulder pads and a raised calf block.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-calf-raise-weight',
      name: 'Weight',
      type: 'number',
      unit: 'kg',
      isRequired: true,
    },
    {
      _id: 'tf-calf-raise-reps',
      name: 'Reps',
      type: 'number',
      unit: 'reps',
      isRequired: true,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 40,
  instructions: [
    'Step onto the calf block with the balls of your feet secure on the edge and heels hanging free.',
    'Position the padded levers comfortably across the tops of your shoulders and stand tall.',
    'Keep your knees soft but extended, core braced, and torso upright.',
    'Lower your heels slowly below the level of the block until you achieve a deep stretch in your calves.',
    'Drive forcefully through the balls of your feet to raise your heels as high as possible into peak contraction.',
    'Pause for a second at the top before descending under control.',
  ],
  notes: [
    'Avoid bouncing out of the bottom stretch; pause briefly to eliminate Achilles tendon elasticity.',
    'Do not bend and straighten your knees to bounce the weight up.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
},
{
  _id: 'ex-incline-treadmill-walk-10-45',
  name: 'Incline Treadmill Walk (10% Incline, 4.5 km/h)',
  description: 'A low-impact steady-state cardiovascular exercise walking uphill on a motorized treadmill to build aerobic endurance while loading the calves, hamstrings, and glutes.',
  category: 'cardio',
  muscles: [
    {
      _id: 'sys-glutes',
      name: 'Glutes',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-hamstrings',
      name: 'Hamstrings',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-calves',
      name: 'Calves',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: false,
      isCustom: false,
    },
    {
      _id: 'sys-quads',
      name: 'Quads',
      region: 'Lower Body',
      group: 'Legs',
      isAnterior: true,
      isCustom: false,
    },
  ],
  tags: ['cardio', 'treadmill', 'incline', 'walking', 'endurance', 'liss'],
  difficulty: 'Beginner',
  equipment: [
    {
      _id: 'eq-motorized-treadmill',
      name: 'Motorized Treadmill',
      description: 'Standard gym treadmill with adjustable digital speed and incline settings.',
      isCustom: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  trackingFields: [
    {
      _id: 'tf-treadmill-duration',
      name: 'Duration',
      type: 'time',
      unit: 'min',
      isRequired: true,
    },
    {
      _id: 'tf-treadmill-speed',
      name: 'Speed',
      type: 'number',
      target: 4.5,
      isRequired: false,
    },
    {
      _id: 'tf-treadmill-incline',
      name: 'Incline',
      type: 'number',
      target: 10,
      isRequired: false,
    },
    {
      _id: 'tf-treadmill-distance',
      name: 'Distance',
      type: 'number',
      unit: 'km',
      isRequired: false,
    },
  ],
  isUnilateral: false,
  estimatedDuration: 1200,
  instructions: [
    'Step onto the treadmill belt and attach the safety lanyard clip to your clothing.',
    'Start the belt at a warm-up pace, then set the incline to 10% and adjust the speed to 4.5 km/h.',
    'Walk upright with shoulders back, eyes forward, and a natural arm swing.',
    'Drive through your heels and midfoot into the belt with each step to engage your glutes and posterior chain.',
    'Upon completion, lower the incline to 0% and reduce speed gradually for a 2-minute cooldown before stopping.',
  ],
  notes: [
    'Avoid gripping the front or side handrails, as leaning on them reduces caloric burn and alters natural walking mechanics.',
    'Keep your torso tall rather than leaning excessively forward at the waist.',
  ],
  authorId: 'system',
  isCurated: true,
  isPrivate: false,
  isShared: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}
]